### PR TITLE
16.0 mig contra accounts

### PR DESCRIPTION
**Pull request by StefanWiselka-Solvti**
Implementing and migrating modules: account_move_line_contra_accounts and account_general_ledger_contra_accounts

Additionally, updated file .pylintrc -> variable: `valid_odoo_versions` config to version 16.0.

### CODE REVIEW

**Comment by StefanWiselka-Solvti** [comment]
Hi @janikvonrotz 

Modules:
account_move_line_contra_accounts,
account_general_ledger_contra_accounts
are ready and can be tested/reviewed.
I hope to get some feedback.

So far, I've spent 7,5h.

Best
Stefan

**Comment by janikvonrotz** [comment]
@MriV13 I was able to install the modules and they work as expected. Thank you very much!

**Comment by StefanWiselka-Solvti** [comment]
> @MriV13 I was able to install the modules and they work as expected. Thank you very much!

Thanks for letting me know.
Best
Stefan

**Comment by StefanWiselka-Solvti** [comment]
@janikvonrotz Hi Janik
I hope you have nice day!
Is there something more which I can help in this module or repository or another tasks?
Best
Stefan (Solvti)

**Pull request merged**
